### ISSUE TITLE
Disabling plants and bug with planting rice

### ISSUE THREAD

**Issue by Circine** [Poulpynou/dawnoftimebuilder#11]
Plants like mulberry and camellia continue to generate in the world even if their blocks and items are disabled. They only drop sticks in this case, but it'd be better if they didn't generate at all.
Rice can be planted in water deeper than one block, leaving it floating. This also tends to happen when targeting a block further away from you; instead of being planted above the solid block you're looking at, it'll be planted in the closer water block the crosshairs are pointed at.

**Comment by ghost** [comment]
I will add a new config file for world generation, and I'm going to fix this problem with rice!
