### ISSUE TITLE
Silkmoths never despawns

### ISSUE THREAD

**Issue by Deadmanovi4** [Poulpynou/dawnoftimebuilder#17]
There a possible lag provider if player build a mulberry farm.
Silkmoths can spawn at any time, not only on morning (thanks, wiki) and not despawns, like any other frienly-neutral creature.
https://imgur.com/a/0pIfTdv

Version of mod: 1.0.7 builders edition
Doesn't require log attachments.

**Comment by ghost** [comment]
This bug was in 1.14, which is a version barely not used. I think I won't fix this one, and focus on the 1.16.
