### ISSUE TITLE
solicitud 

### ISSUE THREAD

**Issue by DragonAstemirN** [Poulpynou/dawnoftimebuilder#18]
Estuve revisando la nueva actualizacion 1.16.5 y me encanta que se haya transladado a esta version, quisiera que las armaduras tuvieran compativilidad con el mod epic-fight, el problema supongo es por las texturas personalizadas
![2022-05-01_18 22 59](https://user-images.githubusercontent.com/94336869/166171574-ef519489-e063-415e-b5be-56473abeb548.png)
.

![2022-05-01_18 23 15](https://user-images.githubusercontent.com/94336869/166171611-e178146b-5136-49e4-b485-5509e25fa26f.png)

![2022-05-01_18 25 41](https://user-images.githubusercontent.com/94336869/166171757-3a3a2d12-bb03-4128-a0fc-ed91d68d13a8.png)

![2022-05-01_18 24 27](https://user-images.githubusercontent.com/94336869/166171766-72116a6e-60ff-481f-be70-a75c6b0e0a4b.png)
unica armadura que casi encaja con las animaciones 
![2022-05-01_18 24 01](https://user-images.githubusercontent.com/94336869/166171805-bdbc23cc-1063-4e94-bc48-85f5cbca4cfa.png)

**Comment by DragonAstemirN** [comment]
revision of the latest update dawnoftime_builder_edition-1.16.5-1.2.3. most visual issues fixed thanks. there are still some armor pieces that have incompatibility with the epic fight mod

![2022-05-08_10 37 35](https://user-images.githubusercontent.com/94336869/167309080-652a21a7-0d64-46d7-a0d0-8b67694c517d.png)

![2022-05-08_10 38 37](https://user-images.githubusercontent.com/94336869/167309110-06b51a3d-0715-4db0-bc60-cab2c7860ff2.png)
![2022-05-08_10 38 50](https://user-images.githubusercontent.com/94336869/167309115-06fcfe11-a9f2-48d0-9a86-7a295beabcc5.png)


small visual bug in this armor piece showing without new animations too
![2022-05-08_10 39 29](https://user-images.githubusercontent.com/94336869/167309222-26cb2c39-9615-44b5-9d3b-a97e369c155c.png)
![2022-05-08_10 39 34](https://user-images.githubusercontent.com/94336869/167309233-a0d1a234-7b33-4f63-88c2-2e3fc0a6eef8.png)
![Inked2022-05-08_10 39 29_LI](https://user-images.githubusercontent.com/94336869/167309237-237129cb-40b4-45d4-abcc-49b54562fdc0.jpg)

![2022-05-08_10 41 44](https://user-images.githubusercontent.com/94336869/167309289-58225b0b-5bd5-4e72-8e45-873c784bfd08.png)
![2022-05-08_10 42 19](https://user-images.githubusercontent.com/94336869/167309298-c4b4b8d3-4050-4f75-8ca8-0e1ade8c0c1c.png)
![2022-05-08_11 15 51](https://user-images.githubusercontent.com/94336869/167309306-21a3d7bf-5f62-4d24-9eeb-9993b751164d.png)
![2022-05-08_11 16 57](https://user-images.githubusercontent.com/94336869/167309320-40363e85-5408-43c1-a029-a3a27f548872.png)

**Comment by ghost** [comment]
Hey ! Yes, I'm currently in touch with the dev of Epic Fight mod to try make our mod compatible. I was able to fix some problems, but some are still there that comes from EFM side. I won't be able to fix it on my own.
The developper from EFM is currently working on it, so hopefully this should be solved one day !

**Comment by DragonAstemirN** [comment]
I also hope that it can be solved thanks I am delighted with your work it is incredible and very well detailed

**Comment by ghost** [comment]
The developper of EFM updated his code in 1.18 but won't in 1.16, which means this problem won't be fixed.
When DoTB will be ported to 1.18 this problem should disappear !
