### ISSUE TITLE
mulberry

### ISSUE THREAD

**Issue by RobinIsNotReal** [Poulpynou/dawnoftimebuilder#21]
when the player touches an unripe mulberry, the world saves, and says the game crashed.
[crash-2022-05-17_12.51.53-client.txt](https://github.com/Poulpynou/dawnoftimebuilder/files/8707372/crash-2022-05-17_12.51.53-client.txt)

**Comment by ghost** [comment]
Hey !
What do you mean exactly with "the player touches an unripe mulberry" ? That you right-clicked on a mulberry block of age 0 ?
I'm trying to reproduce the bug

**Comment by ghost** [comment]
I can't reproduce this problem.

From what I understand, one of the mod you are using in conflicting with dawnoftime. I will to investigate more to find which one is responsible of this bug.

**Comment by RobinIsNotReal** [comment]
by unripe mulberry I mean a mulberry that isn't ready for harvest. I mean any age that doesn't drop an item. im trying to figure out which mod it is too if possible. its one of my first times having trouble with a mod so sorry if this isnt helpful :'(

**Comment by TheGoldenWorld** [comment]
Thanks for detailing your answer :) We will try to look into it deeply but since the crash report doesn't point out DoT or mulberry block it's a bit complicated.

**Comment by RobinIsNotReal** [comment]
its quark that crashes it. it does not happen with other plants as far as I know

**Comment by ghost** [comment]
Ok thank you for the information ! I will check the code
