### ISSUE TITLE
Connected Textures Mod Does Your Mod Dirty

### ISSUE THREAD

**Issue by Art1xs** [Poulpynou/dawnoftimebuilder#22]
Recently, the Connected Textures mod has only caused problems on versions 1.16-1.18, and I would really LOVE to use your mod to create a building world. However, its almost impossible considering that connected textures just crashes with ANY mod. I'm trying to isolate the problem, but I looked at their issues page and its just a whole lot of. "this mod sucks, its outdated and crashes with everything. 

I understand that it takes a whole lot of time to rewrite mods and what not, so this is simply a question. Will you guys divert from using the Connected textures mod in the future? I understand that may not be a possibility, but it does not seem like they are willing to properly update their mod anytime soon...

Love this mod btw, and you guys have done great work updating it to the most recent versions. I will do everything in my power to have this mod on my world lol! # #

**Comment by ghost** [comment]
Hey !
You can already use our mod without Connected Textures Mod, you will just miss the connected textures !

**Comment by Art1xs** [comment]
Really?! I tried removing it in the past, your mod disappeared along with it
... I'll try again.

**Comment by ghost** [comment]
Ok ! Let me know if it works, because if it is not working, we have a problem hahaha

**Comment by Art1xs** [comment]
oh wow, yep, it works!!! 
idk why, but when I had the LOTR: renewed mod installed, it didn't show up. I'll investigate this some more. Maybe It'll work.

**Comment by ghost** [comment]
Ok great !
I checked on their github, and CTM seems to be still in development. Hopefully Tterrag will fix these problems.

I will close this ticket. Do not hesitate if you have any news !
