### ISSUE TITLE
Skin Issue

### ISSUE THREAD

**Issue by EnzoCuervo** [Poulpynou/dawnoftimebuilder#23]
Buenas Tardes a todos. 
Mi problema con el mod es que la armadura de O-yoroi, especificamente el casco, no permite visualizar mi skin. Probe quitando el optifine y tampoco se ve. Alguno sabe como arreglar esto y cual es la causa? Tengo otros mods agregados como el Mo´bends, pero no resulto ser el problema y ya lo quite para probar si era este el problema. 

/////

Good afternoon everyone.
My problem with the mod is that O-yoroi's armor, specifically the helmet, doesn't allow me to see my skin. I tried removing the optifine and it doesn't show either. Does anyone know how to fix this and what is the cause? I have other mods added like Mo'bends,
but it did not turn out to be the problem and I already removed it to test if this was the problem.

**Comment by ghost** [comment]
Hey !
I'm not sure to understand your problem. Can you show me a screenshot ?

**Comment by EnzoCuervo** [comment]
Yes sir, but Im not at home now. In 4 hours I will so, when I come back Ill
post it

**Comment by EnzoCuervo** [comment]
> Hey ! I'm not sure to understand your problem. Can you show me a screenshot ?
![Minecraft 1 12 2 1_7_2022 19_39_43](https://user-images.githubusercontent.com/108543479/176977969-edba5a62-0a61-4e9f-bd18-05b4f56ad8d2.png)

**Comment by EnzoCuervo** [comment]
apparently it's not just that mod, it happens with others too.

**Comment by ghost** [comment]
Ho you are using an animation mod ! Is it Epic Fight Mod ? Anyway, custom armors are not compatible with these mods.
I talked to the developper of EFM and this problem will be fixed in 1.18. There wont be a fix for 1.16

**Comment by EnzoCuervo** [comment]
> Ho you are using an animation mod ! Is it Epic Fight Mod ? Anyway, custom armors are not compatible with these mods. I talked to the developper of EFM and this problem will be fixed in 1.18. There wont be a fix for 1.16

Oh, well. I wont die if I dont see my face, my beautiful face.
