### ISSUE TITLE
Birch couch

### ISSUE THREAD

**Issue by firmeon** [Poulpynou/dawnoftimebuilder#25]
Hello,

I use your mod for some decoration but I discover a small duplication bug.
When you break a birch couch, two birch couch items drops.
It's maybe because it's a bock who is two block large and the loot tables doesn't work ?

Sorry for my bad english, i'm French.

**Comment by ghost** [comment]
Salut et merci pour le ticket ! Je suis FR aussi donc je te reponds en français.
Effectivement c'est lié au fait que le block soit composé de 2 parties. J'ai probablement fait une erreur dans le fichier de la loot_table ! Je vais resoudre ça
