### ISSUE TITLE
Silk worm bug

### ISSUE THREAD

**Issue by TheAJH** [Poulpynou/dawnoftimebuilder#26]
So i downloaded Dawn of time into a custom modpack with some friends and I looked to find silk worms, I checked a dozen biomes to find none, So we spawned me the plant and the egg to get started because of I couldnt find them, i then was able to get silk but then recently I placed the hatchery on the drying plate and when it finished it was an empty plate and I didnt get the silk worms.

**Comment by Deadmanovi4** [comment]
Silkmoths start to spawn, if some grown bushes from mod nearby. Also don't make big farm with these bushes. Silkmoths doesn't despawn normally.

**Comment by TheAJH** [comment]
thanks it just started working, I dont know what did it but the mod just now started working again
