### ISSUE TITLE
[1.20.1] Not all blocks breakable in survival

### ISSUE THREAD

**Issue by Razsiel** [Poulpynou/dawnoftimebuilder#35]
*As-is*
Having just added this mod to my modpack I noticed that despite items being craftable in survival, once placed down a few items don't have a tool/breaking configured (Jade mod is also not reporting a tool to be used for some and breaking-progress is red), causing it to take longer to break than necessary.

Haven't tested every block, but the list below should help track down what the issue is.

*Current (known) list of blocks*

**No-tool + no-hardness (breaks with obsidian-speed):**
- Stone brick fireplace (Limestone is fine oddly enough!)
- Candlestick
- Portcullis
- All marble
- Plastered stone + variants
- Roofing
- Stone brick chimney

**No-tool (breaks with stone-speed):**
- All wood variants (edge, plate, pergola, etc)
- All paper blocks
- All Thatch

**Comment by TheGoldenWorld** [comment]
Hi, thank you for taking the time to detail the bug report :) 
We are aware of this issue, I spend most of my evening checking individualy each block ☠️ Now that we have the full list we will fix that asap !

**Comment by PierreChag** [comment]
Hello !
I think this bug should be fixed now, so I will close this issue. Feel free to open it again, or create a new one if you find anything else :)
