### ISSUE TITLE
Lattice Stone Brick Windows Render Incorrectly

### ISSUE THREAD

**Issue by WenXin20** [Poulpynou/dawnoftimebuilder#38]
```
Minecraft v1.20.1
Dawn of Time v1.3.3
```

I believe the render type was not set in the block model.

![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/12000593/83080fdb-728a-42b1-b568-8f4dc01e13f3)

**Comment by PierreChag** [comment]
Hello !

You are right, I forgot to set the render type fir these models. I just fixed it, this bug won't be in the next release of the mod !

Thank you for the report 👌
