### ISSUE TITLE
Red Sapling Breaks Blocks

### ISSUE THREAD

**Issue by WenXin20** [Poulpynou/dawnoftimebuilder#40]
When the sapling grows, it breaks all the blocks around it, including bedrock
![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/12000593/87ed3190-f792-4645-98c4-c7060564a80f)

**Comment by WenXin20** [comment]
Also, middle-clicking the leaves in creative gives you the acacia beam

**Comment by PierreChag** [comment]
Wow indeed it's not supposed to do this !
Let me fix this issue :)

**Comment by PierreChag** [comment]
I just fixed this bug, it won't be in the next release !
Thank you again for the report, and feel free to open a new ticket if you find anything :)

**Comment by WenXin20** [comment]
No problem!
