### ISSUE TITLE
Waxed Oak uses spruce for the recipe

### ISSUE THREAD

**Issue by WenXin20** [Poulpynou/dawnoftimebuilder#41]
Waxed Oak uses spruce for the recipe.
![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/12000593/ff78a3bf-c9bb-405a-95f7-b877200b9618)

Also, is it normal that the spruce support has a white ends texture?
![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/12000593/2b880015-1549-46c4-8fce-b1a7592314c2)

**Comment by PierreChag** [comment]
Hello !
Thank you for the report and sorry for the late answer. Indeed it's mistake, I will fix this craft asap.

Regarding the texture, I went to japan and saw that all the "roof support" ends were painted in white. But indeed the texture in my mod is too flat, and looks strange ! I will add some noise to make it more natural.

![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/79593151/216bfa49-df36-414f-b1f4-a9c18a8dff63)

**Comment by PierreChag** [comment]
I just fixed both issues, thank you for the report !

Feel free to reopen this issue if needed, or create a new ticket :)
