### ISSUE TITLE
Crash with Dramatic Doors

### ISSUE THREAD

**Issue by WenXin20** [Poulpynou/dawnoftimebuilder#42]
```
Minecraft v1.20.1
Dawn of Time v1.3.3
```

The dramatic doors mod crashes with this mod as it adds waterlogging to all fence gates and doors as well, so the game crashes due to a duplicate blockstate.

https://gist.github.com/WenXin20/770a1ab302c2876f4a556c9303320416

**Comment by Kitteh6660** [comment]
The fix is planned to be in next version of Dramatic Doors.

**Comment by TheGoldenWorld** [comment]
Hi @Kitteh6660 , I marked your mod as an incompatibility with DoT:BE on CF. When you succeed to fix the bug may you can notify us on this post or something ? I will also take a look at your mod to spot the update :) People seems to like playing with both or our mods !

**Comment by Kitteh6660** [comment]
Here's the upcoming fix! Now it's a matter of getting the Mixin mappings working.
![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/5838739/975c2e5d-dd4e-4cb3-b730-385a0be7fdde)

**Comment by TheGoldenWorld** [comment]
The famous door army. Impressive

**Comment by Kitteh6660** [comment]
The fix should now be live in mod version 3.2.1 for Minecraft 1.20.1.

This works by using Mixin to cancel adding waterlogged property to allow the modded doors and fence gates to naturally inherit from their superclass.

**Comment by PierreChag** [comment]
Great ! I saw that you published this version !
Thank you for your help :)
