### ISSUE TITLE
1.20.1 Block placement

### ISSUE THREAD

**Issue by FidoDestroyer** [Poulpynou/dawnoftimebuilder#46]
the table is placed not on the tatami but in the air; in the video guide it is placed on the tatami
![2024-05-14_14 41 31](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/55804852/793ec03a-b957-40ed-bcce-33050431ea6d)

**Comment by FidoDestroyer** [comment]
![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/55804852/3dee8ca4-f4b2-4fbc-b1d4-297ad39c1d9b)
video

**Comment by PierreChag** [comment]
Hello Fidodestroyer !
Indeed there is a little trick. If you place your tatamis on spruce planks, the tatami "merges" with the planks bellow, which allows you to place correctly the table.

I know it's not a very efficient behavior, it will be reworked in futur updates !

**Comment by FidoDestroyer** [comment]
> Hello Fidodestroyer ! Indeed there is a little trick. If you place your tatamis on spruce planks, the tatami "merges" with the planks bellow, which allows you to place correctly the table.
> 
> I know it's not a very efficient behavior, it will be reworked in futur updates !


thanks, it worked
