### ISSUE TITLE
1.20.1 textures don't connect

### ISSUE THREAD

**Issue by FidoDestroyer** [Poulpynou/dawnoftimebuilder#47]
the door and the wall won't connect
![2024-05-14_14 47 54](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/55804852/55f9a964-7600-4e26-93b7-e16097e4e6de)

**Comment by PierreChag** [comment]
Are you using the last version of the mod ? This bug was fixed in DoT 1.5.6 (at least it should).

**Comment by FidoDestroyer** [comment]
> Are you using the last version of the mod ? This bug was fixed in DoT 1.5.6 (at least it should).

yes, it's 1.5.6

**Comment by PierreChag** [comment]
All right, I will check this evening !

**Comment by FidoDestroyer** [comment]
> All right, I will check this evening !

oh, after I opened the doors they connected, before that i build the doors in the previous version

**Comment by TheGoldenWorld** [comment]
Thanks for your bug report ! I close the issue now :p
