### ISSUE TITLE
Crash ticking Lattices

### ISSUE THREAD

**Issue by katubug** [Poulpynou/dawnoftimebuilder#55]
[crash-2024-09-09_18.56.16-server.txt](https://github.com/user-attachments/files/16937673/crash-2024-09-09_18.56.16-server.txt)

Minecraft 1.20.1
Forge 47.3.1
Dawn of Time 1.5.8

Got this crash today while afking. I think it's because I placed vines on a lattice above another lattice I'd placed vines on. Like this:
![2024-09-09_19 01 06](https://github.com/user-attachments/assets/73a8a26e-a6b8-48b2-bda6-e367ce3086ae)

I placed vines on the bottom ones and then also on the middle ones while I was just messing around and seeing how things worked. I assume the bottom ones tried to grow up and onto the middle ones but couldn't because there were already vines there?

**Comment by PierreChag** [comment]
Hey !
This bug has been fixed and won't be present in the next release :)
Thank you for your report !
